### ISSUE TITLE
预训练的模型

### ISSUE THREAD

**Issue by lhy2749** [SunnyGJing/t5-pegasus-chinese#2]
您好，我看您使用了bert4keras，所以这两个百度云的模型是在追一的那个模型基础上转化或者继续训练得到的吗？

**Comment by SunnyGJing** [comment]
您好，这两个百度云的模型是在追一的Keras版本模型基础上转化为了Pytorch版本。这两个百度云的模型没有继续训练。

**Comment by lhy2749** [comment]
@SunnyGJing 所以百度云真的没有放错么？我为什么点开看到的还是原版苏神分享的tf版本的模型？

**Comment by SunnyGJing** [comment]
@lhy2749 是的，百度云链接放错了，感谢告知啦。我用的是renmada分享的torch版本模型，我更新了README.md。
