### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by si-tu-xiao** [SunnyGJing/t5-pegasus-chinese#3]
![image](https://user-images.githubusercontent.com/94363522/141769821-ddd0b918-6b8b-4081-b954-236a93886df4.png)

After running your code, an error occurs, have you ever met?

**Comment by SunnyGJing** [comment]
Hi,

Sorry. I haven't ever met this error message. **You may need to download and change to the new pretrained model updated in README.md.**

Please tell me something about the following:
1. The version of your **transformers** package (4.3.3 or not?)
2. **Base** model or **Small** model you used (base or small?)
3. Have you made any changes to the code?

**Comment by si-tu-xiao** [comment]
> Hi,
> 
> Sorry. I haven't ever met this error message. **You may need to download and change to the new pretrained model updated in README.md.**
> 
> Please tell me something about the following:
> 
> 1. The version of your **transformers** package (4.3.3 or not?)
> 2. **Base** model or **Small** model you used (base or small?)
> 3. Have you made any changes to the code?

**Comment by si-tu-xiao** [comment]
here is the info:
1、the version of transformers is 4.3.3, actually the version of packages  I used was just as you required in the README.md.
2、I tried both models(base/small).
3、I did nothing to the code.

**Comment by si-tu-xiao** [comment]
the updated pytorch model in README.md works.
